export const supabaseFa = {
  variables: {
    sign_up: {
      password_label: "رمز ورود",
      email_label: "آدرس ایمیل",
      email_input_placeholder: "ایمیل",
      password_input_placeholder: "رمز ورود",
      button_label: "ثبت نام",
      loading_button_label: "در حال ثبت نام ...",
      social_provider_text: "ثبت نام با {{provider}}",
      link_text: "از قبل ثبت نام نکردید؟ ثبت نام",
      confirmation_text: "آدرس ایمیل خود را برای تاییدیه چک کنید",
    },
    sign_in: {
      email_label: "آدرس ایمیل",
      password_label: "رمز ورود",
      email_input_placeholder: "ایمیل",
      password_input_placeholder: "رمز ورود",
      button_label: "ورود",
      loading_button_label: "در حال ورود ...",
      social_provider_text: "ورود با {{provider}}",
      link_text: "از قبل اکانت دارید؟ ورود",
    },
    magic_link: {
      email_input_placeholder: "ایمیل",
      email_input_label: " آدرس ایمیل",
      button_label: "ثبت نام",
      loading_button_label: "در حال ورود ...",
      link_text: "ارسال لینک جادویی به ایمیل",
      confirmation_text: "ایمیل خود را چک کنید",
    },
    forgotten_password: {
      email_label: "آدرس ایمیل",
      password_label: "رمز ورود",
      email_input_placeholder: "ایمیل",
      button_label: "ورود",
      loading_button_label: "در حال ارسال راهنمای بازیابی",
      link_text: "رمز خود را فراموش کردید؟",
      confirmation_text: "ایمیل خود را برای بازیابی رمز چک کنید",
    },
    update_password: {
      password_label: "رمز جدید",
      password_input_placeholder: "رمز جدید",
      button_label: "تغییر رمز",
      loading_button_label: "در حال بروزرسانی رمز ...",
      confirmation_text: "رمز شما تغییر کرد",
    },
    verify_otp: {
      email_input_placeholder: "ایمیل",
      email_input_label: " آدرس ایمیل",
      phone_input_label: "شماره تلفن",
      phone_input_placeholder: "شماره تلفن",
      token_input_label: "توکن",
      token_input_placeholder: "رمز یکبار مصرف ",
      button_label: "تایید توکن",
      loading_button_label: "در حال ورود",
    },
  },
};
